//
// Generated file, do not edit! Created by nedtool 5.6 from IpPacket.msg.
//

#ifndef __IPPACKET_M_H
#define __IPPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>IpPacket.msg:2</tt> by nedtool.
 * <pre>
 * message IpPacket
 * {
 *     unsigned char payload[1500];
 * }
 * </pre>
 */
class IpPacket : public ::omnetpp::cMessage
{
  protected:
    unsigned char payload[1500];

  private:
    void copy(const IpPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IpPacket&);

  public:
    IpPacket(const char *name=nullptr, short kind=0);
    IpPacket(const IpPacket& other);
    virtual ~IpPacket();
    IpPacket& operator=(const IpPacket& other);
    virtual IpPacket *dup() const override {return new IpPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getPayloadArraySize() const;
    virtual unsigned char getPayload(unsigned int k) const;
    virtual void setPayload(unsigned int k, unsigned char payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IpPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IpPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __IPPACKET_M_H

